// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220419211234_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "Vestuário",
                            Description = "Description",
                            ImageUrl = "https://www.camisetas4fun.com.br/media/product/7e2/camiseta-one-piece-1c2.jpg",
                            Name = "Name 2",
                            Price = 169.90000000000001
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Vestuário",
                            Description = "Description 4",
                            ImageUrl = "https://cf.shopee.com.br/file/f2fd18b782a1ab556c35f03f443f58a1",
                            Name = "Name 4",
                            Price = 619.89999999999998
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Papelaria",
                            Description = "Description 5",
                            ImageUrl = "https://www.camisetas4fun.com.br/media/product/7e2/camiseta-one-piece-1c2.jpg",
                            Name = "Name 5",
                            Price = 269.89999999999998
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Vestuário",
                            Description = "Description 6",
                            ImageUrl = "https://a-static.mlcdn.com.br/618x463/camisa-camiseta-one-piece-monkey-d-luffy-manga-home-custom/diasoutlet/30774fcc058f11ecb5264201ac185013/6e9c651f7666e1b720c9fe0987fc12c0.jpg",
                            Name = "Name 6",
                            Price = 629.89999999999998
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Papelaria",
                            Description = "Description 7",
                            ImageUrl = "https://cf.shopee.com.br/file/f2fd18b782a1ab556c35f03f443f58a1",
                            Name = "Name 7",
                            Price = 692.89999999999998
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Papelaria",
                            Description = "Description 8",
                            ImageUrl = "https://www.camisetas4fun.com.br/media/product/7e2/camiseta-one-piece-1c2.jpg",
                            Name = "Name 8",
                            Price = 691.89999999999998
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Vestuário",
                            Description = "Description 9",
                            ImageUrl = "https://a-static.mlcdn.com.br/618x463/camisa-camiseta-one-piece-monkey-d-luffy-manga-home-custom/diasoutlet/30774fcc058f11ecb5264201ac185013/6e9c651f7666e1b720c9fe0987fc12c0.jpg",
                            Name = "Name 9",
                            Price = 619.89999999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
